### ISSUE TITLE
Cursor?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1338]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:adangit107@gmail.com<br><br>Is there a feature within easy canvas that allows my apple pencil to display my cursor while hovering?<br><br>[EL_Display_15d00b02-ff88-450b-8300-4667f0c64d17.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_15d00b02-ff88-450b-8300-4667f0c64d17.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.

The cursor doesn't always show up.

It cannot be supported because hovering is not possible technically.

Sorry for the inconvenience.

But, I will convey it to our development team.

We will do our best for a better program.

Thanks.

Easy&Light
