### ISSUE TITLE
PC 프로그램 표시 불가 및 기능 동작 불가 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#1393]
- 문의 날짜 : 2022년 9월 3일 오전 10시 19분
- 메일 주소 : officialpokepastel@gmail.com

Title: Issue displaying properly on iPad Pro and Eldisplayhub opening

Questions: I am seeing that this app has been displaying everything in super high contrast and brightness. I am trying to use this app as a drawing tablet for photoshop and while my pc displays all colors correctly, I can\'t even see light colors or colors with low opacity on the iPad. I tried changing my iPad Pro\'s brightness settings, turning off the increase contrast setting, pressure sensitivity, the app\'s resolution, and performance mode but nothing is working. Maybe it\'s a monitor issue? My monitor is an ASUS 27\"LED VG27WQ1B

Also, I just noticed that the EL Display HUB is no longer opening on my pc. This has happened for 2 days while I\'ve only had the app for 3 days now. I tried reinstalling it and it opened fine but when I minimized it I could no longer open it.

![IMG_0579](https://user-images.githubusercontent.com/77039816/188341409-69c4a9fb-e42b-4166-b979-3f89bf181070.png)

**Comment by Sienna-lee** [comment]
해당 사용자에게 로그파일을 요청하였습니다.

----


Hello, customer. We are an Easy & Light support team.

First of all, we apologize for the inconvenience.


Could you please send us the log file so we can check the problem?
Our technical team will solve your problem.


[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54


If it is difficult to attach log files, please contact us through 'Inquiry' of EL Display Hub. The log is automatically attached.


Thank you.

Easy & Light

**Comment by Juilliardsong** [comment]
개발팀에 문의한 결과 문제 화면 색상 문제는 바로 해결이 어렵다고 합니다.
고객에게 환불 가이드 전달했고, 색상 문제를 감안하고 쓸 경우 연결불가 이슈를 해결하기 위한 로그 요청을 다시 하였습니다.

----
Hello, customer. We are an Easy & Light support team.

As a result of checking with the development team, if you send a log, the problem that cannot be connected can be analyzed and resolved.
However, it is said that the problem of color on the screen is difficult to solve because it cannot be reproduced.


If it is difficult to use due to color problems, you can get a refund through the Apple App Store.
According to Apple policy, the developer cannot cancel the subscription, and the user must cancel the subscription himself.

If payment has been made, you can request a refund from Apple.
https://support.apple.com/en-us/HT204084


If you use it considering the color problem, we will solve the problem of not connecting.
Looking at the email you sent, the log file was not properly attached.
If you submit an inquiry through [Support] - [Inquiry] of the PC Program (EL Display Hub), the log is automatically attached.
Please use "officialpokepastel@gmail.com" as your email address when sending.

![image](https://user-images.githubusercontent.com/68727895/188780886-0f04e330-2941-4deb-a570-d834058c0a46.png)
![image](https://user-images.githubusercontent.com/68727895/188780910-6baa834c-4d54-492a-961f-24a8a25a1bd4.png)


Thank you.
Easy&Light
