### ISSUE TITLE
[EasyCanvas - Mac] Easyconvas Pro does not get started

### ISSUE THREAD

**Issue by Juilliardsong** [edh-git/EL_Display_Hub#1537]
메일을 통해 접수된 VOC입니다.
---
Select product: EasyCanvas
OS: Mac
Device: iOS
Category: Functional problems
Name: volantis volantis
메일: volantisccial@netcourrier.com

Title: Easyconvas Pro does not get started

Questions: Easyconvas Pro does not get started on MacOS Ventura 13.1 on Ipad OS 16.2 there is no problem but it\'s useless
Thanks for your answer

mailing: no
Log File (PC): adb-2022-11-10-013134.0002.ips
Log File(Device): adb-2022-11-10-013134.0002.ips
Image:

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello,  We are an Easy & Light support team.

I'm sending this email for your inquiry.


The log file was not properly attached.

First, uninstall the program for Mac and then reinstall it.

If the problem is not resolved, please re-extract the log file and attach it.

Please refer to the log extraction guide below.


http://www.easynlight.com/en/supporteasycanvas/?faq=54


Please attach log files for both Mac and iOS.
I will forward your log files to the technical team.


Thank you.

Easy&Light
