### ISSUE TITLE
it doesn't connect

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1581]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:sunrise.omar89@gmail.com<br><br>it won't connect and i've checked everything and tried uninstalling and then reinstalling the app<br><br>[EL_Display_7cdeff54-be23-4714-b84f-9873f9742415.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_7cdeff54-be23-4714-b84f-9873f9742415.zip)

**Comment by AdamPark0030** [comment]
## 원인 파악

디스플레이 edid 정보를 읽어오지 못하여 proc이 재시작됨을 반복함.

관련 이슈 : https://github.com/devguru-co-ltd/bypd/issues/64

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

## 답변

Hello, this is the Easy & Light support team.

There seems to be a problem because the screen information cannot be obtained from the display you are using.

Try connecting another monitor that you can connect to, or change the cable that connects the PC to the monitor.

If you are unable to do so, we are sorry to inform you that you cannot use it in your environment at this time, so we will give you a refund.

Below is the refund method.

[Refund guide]

Playstore for Android
If you access the link below, fill out the necessary information, and submit it, we will check and proceed with the refund process.
[Android] TwomonAir/TwomonUSB/Twomon SE 
[a refund request]
https://docs.google.com/a/devguru.co.kr/forms/d/1o4dSUJnXx7edy8DRU7GNvgOOEppsJ2WWh0btjHh9Lb4

App Store for iOS
All apps sold on the Apple App Store are managed by Apple. We do not have the right to proceed with the application refund because we do not have your purchase information. Please refer to the link below.
Link to Apple Support site:
https://reportaproblem.apple.com/﻿

How to get a refund from the iTunes store:
https://support.apple.com/ko-kr/HT204084

Thank you.

Easy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Easycanvas - 1581] it doesn't connect
```
#### 본문
```
Hello, this is the Easy & Light support team.

There seems to be a problem because the screen information cannot be obtained from the display you are using.

Try connecting another monitor that you can connect to, or change the cable that connects the PC to the monitor.

If you are unable to do so, we are sorry to inform you that you cannot use it in your environment at this time, so we will give you a refund.

Below is the refund method.

[Refund guide]

Playstore for Android
If you access the link below, fill out the necessary information, and submit it, we will check and proceed with the refund process.

[Android] TwomonAir/TwomonUSB/Twomon SE
a refund request : https://docs.google.com/a/devguru.co.kr/forms/d/1o4dSUJnXx7edy8DRU7GNvgOOEppsJ2WWh0btjHh9Lb4

App Store for iOS
All apps sold on the Apple App Store are managed by Apple. We do not have the right to proceed with the application refund because we do not have your purchase information. Please refer to the link below.
Link to Apple Support site:
https://reportaproblem.apple.com/﻿

How to get a refund from the iTunes store:
https://support.apple.com/ko-kr/HT204084

Thank you.

Easy&Light
```
