### ISSUE TITLE
I can't seem to install PC programs correctly

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1590]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:448010582@qq.com<br><br>This is my log. When I install a pc program, it always flashes back at some point and shows that the installation is complete. I don't think it was successfully installed.<br><br>[EL_Display_1d0da551-de68-4265-9491-aed95ac87dd8.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_1d0da551-de68-4265-9491-aed95ac87dd8.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

## 답변

Hello, this is the Easy & Light support team.

There seems to be a problem because the screen information cannot be obtained from the display you are using.

Try connecting another monitor that you can connect to, or change the cable that connects the PC to the monitor.

If you are unable to do so, we are sorry to inform you that you cannot use it in your environment at this time, so we will give you a refund.

Below is the refund method.

[How to get a refund]

App Store for iOS
We'd like to give you a refund but we are not in charge of the refund. We'll let you know how to get the refund from the iTunes store. Please refer to the following websites.
Contact Apple Support:
https://reportaproblem.apple.com/

How to get a refund from iTunes store:
https://support.apple.com/en-us/HT204084

Google play store for Android
Please click the following link, fill out and submit a refund request form.
https://docs.google.com/forms/d/1q0_e3fDsvldj5KLzch2OfUBKFCqcluPGNYAyT8TMt7Y/
Thank you.

Easy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1590] I can't seem to install PC programs correctly
```
#### 본문
```
Hello, this is the Easy & Light support team.

There seems to be a problem because the screen information cannot be obtained from the display you are using.

Try connecting another monitor that you can connect to, or change the cable that connects the PC to the monitor.

If you are unable to do so, we are sorry to inform you that you cannot use it in your environment at this time, so we will give you a refund.

Below is the refund method.

[How to get a refund]

App Store for iOS
We'd like to give you a refund but we are not in charge of the refund. We'll let you know how to get the refund from the iTunes store. Please refer to the following websites.
Contact Apple Support:
https://reportaproblem.apple.com/

How to get a refund from iTunes store:
https://support.apple.com/en-us/HT204084

Google play store for Android
Please click the following link, fill out and submit a refund request form.
https://docs.google.com/forms/d/1q0_e3fDsvldj5KLzch2OfUBKFCqcluPGNYAyT8TMt7Y/
Thank you.

Easy&Light
```
