### ISSUE TITLE
Failed to Initialize Encoder

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1602]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:igorlmatos@gmail.com<br><br>The program keeps losing the connection with the iPad. After a few cycles of connection and dysconnection, the attached message shows. I tried restarting the pc and the program, but the problem persists. What should I do?<br><br>[EL_Display_f9e5ea55-4d56-43be-aa4c-ef44261682fa.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_f9e5ea55-4d56-43be-aa4c-ef44261682fa.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

## 답변

Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

After reviewing the logs and symptoms you sent me,

The network state is unstable and appears to be disconnecting. Try the method below.


It was caused by a network speed problem, so please apply the following method.
1. Connect to wireless network 5ghz band
2. Move the wireless network signal strength to the nearest location
3. Laptop Wired Network Connection
4. Connected to iPad by wire to iPad

If the problem persists after taking the above measures, please contact us again with the new PC log and application log.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1602] Failed to Initialize Encoder
```
#### 본문
```
Hello, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

After reviewing the logs and symptoms you sent me, The network state is unstable and appears to be disconnecting. Try the method below.


It was caused by a network speed problem, so please apply the following method.
    1. Connect to wireless network 5ghz band
    2. Move the wireless network signal strength to the nearest location
    3. Laptop Wired Network Connection
    4. Connected to iPad by wire to iPad

If the problem persists after taking the above measures, please contact us again with the new PC log and application log.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Ea​​sy&Light
```
