### ISSUE TITLE
Help with updates

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1630]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:ellebaston@gmail.com<br><br>I purchased Easy Canvas on June 2022, and while the version on the iPad is up to date at 4.6.8, EL Display Hub is on version 4.6.6.0. Are Easy Canvas and EL Display Hub supposed to be in sync with their updates or is this a problem with updating to the latest version that needs to be fixed?<br><br>[EL_Display_d659632c-2b2c-4cf1-81ac-2c1b3fb192dd.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d659632c-2b2c-4cf1-81ac-2c1b3fb192dd.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



Hello, We are an Easy&Light support team.

I'm sending this mail for your inquiry.

You are using the latest version of both the app and the PC program.

The version of the app and the PC program are not the same.

If you have any other issues, please contact us.

Thanks.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Thank you for your helpful response! I do have some other concerns about the program with regards to bugs and possible future updates though. 

I use EasyCanvas on a 2016 iPad Pro with a Windows 10 desktop computer, and when I pan and zoom, sometimes the screen randomly slips and slides away from my gestures, and I don't know if this is a setting that needs to be adjusted or if this is a bug in the program. Also when I make a stroke on my canvas, my cursor stays stuck on the last part of the screen that my pencil touched (turning off the cursor within my drawing program isn't a good fix for me, since I depend on having my brush stroke preview visible for my workflow).

Apart from these suggestions for big fixes, I was wondering if there were any future plans to implement the hover feature introduced in the M2 iPad models in a future update. Do you have any other social media outlets besides your blog and your Facebook page (which haven't been updated in a long time) where customers can get news on future product iterations?

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, We are an Easy&Light support team.

I'm sending this mail for your inquiry.

If you think it's a bug, could you please send us the log files of your PC and the app?
We will send you a manual log file extraction guide at the bottom of the email.
Our technical team will check the problem and give you a solution.


Addition of hover function is currently under review.
When new features are added we will notify you via EasyCanvas Instagram.

https://www.instagram.com/easycanvas_official/



[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save

2. Files existing in the path C:\ProgramData\devguru

3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)


Please zip the three files and attach them.

[App log collection procedure]

　1. Android
　　① Re-run the application on your device.
　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.


　2. iOS
　　① Connect the device to extract the logs to a PC.
　　② Run iTunes and click it when the connected device appears on the upper tap.
　　③ Click ‘File Sharing’ in the list to the left.
　　④ Scroll down the updated screen and click the app (EasyCanvas) to extract the log from the ‘App’ in the ‘File Sharing’ column. 
　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　



Please zip the all files and attach them.



Thank you.

Easy & Light
