### ISSUE TITLE
No Coursor

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1641]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:j.teuffel@icloud.com<br><br>Hi ist there a way to see my courcor (brush size)?<br><br>[EL_Display_074a150c-27be-4df4-9b20-f854c04d7f00.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_074a150c-27be-4df4-9b20-f854c04d7f00.zip)

**Comment by RachelOh** [comment]
아래와 같이 답변
----
Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.

The cursor doesn't always show up.

It cannot be supported because hovering is not possible technically.

Sorry for the inconvenience.

But, I will convey it to our development team.

We will do our best for a better program.

Thanks.


Easy&Light
