### ISSUE TITLE
업데이트 후 연결불가 & 밝기 문제(검정색 색상 표시 문제)

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#226]
e-mail:daniel11021988@mitschang-manda.de<br><br>The TwomonSE app on the iPad doesn't work with this new updated server software anymore, and it has uninstalled the functioning Twomon driver. What is going on with this update??<br><br>Daniel<br><br>[EL_Display_d8e92f3e-a0de-4846-bdba-163c30931e76.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d8e92f3e-a0de-4846-bdba-163c30931e76.zip)

**Comment by AdamPark0030** [comment]
+ 확인중

**Comment by AdamPark0030** [comment]
아래와 같이 답변 부탁드립니다.
----
```
Hello, customer. We are an Easy & Light support team.

First of all, I'm very sorry for the inconvenience of using it.

Currently, there are many inquiries about updates, so the answer is delayed.

The update on the application side does not seem to work properly due to excessive EL Display Hub updates.

After the EL Display Hub update, please visit the tablet's App Store or Google Play Store to manually check for application updates.

If it does not work normally even after updating the application on the tablet side, the PC program may have been damaged during the update process.

Please remove the EL Display Hub on the PC side and install a new installer and reinstall it.

[EL Display Hub] Installation page: http://www.easynlight.com/en/easycanvas/

Thank you.

Easy&Light.
```

**Comment by AdamPark0030** [comment]
사용자에게 답변 완료했습니다.

**Comment by Sienna-lee** [comment]
해당 사용자로부터 아래와 같이 회신이 왔습니다. 

----

Thanks for the information. Earlier when I installed the PC app update, there was no update available for the iOS app yet. Now there is an update available, but I am hesitating to update.

What exactly is the benefit of this update for a TwomonSE user?

Thanks.

Daniel

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.
----


Hello, customer. We are an Easy & Light support team.

Currently, the latest version of Twomon SE - iOS is 4.6.1.

Twomon SE and EasyCanvas have been updated as an integrated PC program to improve performance and ease of use.


If you update, you can experience improved performance.
If you have any questions about the product, please feel free to contact us.


Thank you.

Easy&Light.

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.


----

Hello?

If I use only TwomonSE an an app on the iPad, what benefit will the new updates for the app and the PC app will have for me? Please, I want to figure out if it is worth for me trying to update or not.

Thanks.

Cheers
Daniel

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.


We improved performance with this update.

If you are using the latest PC and iPad, you will notice the improved performance.


If you have any further questions, please contact us.

We will try to make a better program.


Thank you.

Easy & Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Thanks for your reply.

With my current version I do not notice any performance issues. Could you please describe that improved performance a bit more detailed? Is it about latency, or resolution or bitrate?

Thanks.

Best regards
Daniel

**Comment by Sienna-lee** [comment]
@Juilliardsong 

해당 사용자가 업데이트로 어느 부분이 개선되었는지 구체적으로 알려달라고 답변이 왔습니다.
이에 대한 답변 요청드립니다.

**Comment by Sienna-lee** [comment]
@Juilliardsong 

해당 사용자가 아래와 같이 한번 더  회신하였습니다.

-----

﻿With my current version I do not notice any performance issues. Could you please describe what exactly has been improved? How does it manifest?

Is it the CPU performance on the PC which got improved?

I need this information before updating.

Best regards
Daniel

**Comment by Juilliardsong** [comment]
@Sienna-lee 
업데이트 내용입니다. 이렇게 알려주면 될 것 같습니다.

---
이번 업데이트로 하드웨어 가속을 사용하여 NVIDIA 그래픽 환경에서 더 원활하게 사용할 수 있도록 변경되었고, 화질 개선도 이루어졌습니다.
사양이 낮은 PC 및 태블릿을 사용한다면 많은 차이는 없겠지만, 더 좋은 환경에서 사용할수록 더 쾌적하게 사용하실 수 있을 것 같습니다.

계속해서 더 좋은 화질에서 빠른 반응속도를 사용할 수 있게 업데이트 될 예정입니다.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.

With this update, hardware acceleration is used to enable smoother use in the NVIDIA graphics environment, and image quality has been improved.
If you use a low-spec PC or tablet, there won't be much difference, but the more you use it in a better environment, the more comfortable you will be able to use it.


Thank you.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.


-----

Hello. I finally updated to your latest iOS app and PC app version, but I already regret it. There are 2 major issues with it.

Problem 1 )
Glitches:
Here I recorded a video with the native screen capturing feature on the iPad. As you can see there are major glitches going on in this color selection window of Photoshop, and also when dragging the window around you can see smearing. I didn't have that at all with the previous version.

Video:
https://drive.google.com/file/d/16Nv26PvK28E3p-BT9ek_PgftCa5iRnDQ/view?usp=drivesdk


Problem 2 )
Contrast / Blacks:

The image is overall brighter, which makes black not being true black anymore. For this I also made a test. I created in Photoshop a png file with 100 % black color. RGB #000000.
First I screenshotted that file through the Twomon app. Then I opened the exact same file natively directly on the iPad and compared the two. Here is a screenshot of both compared, the left one being a screenshot of the Twomon app and the right one the same file natively displayed on the iPad:

https://files.manda-audio.com/?file_ids=aZbIk0Ot5p3v&title=twomon+true+black+comparing

As you can see, the left one is not the same true black as the right one.

I didn't have that with the previous version either and I instantly noticed it when starting the new version of the app by only looking at the black Windows 10 task bar.

Question:
Are you going to do something about it? Is there any fixing planned very soon? If not, I would like to have a possibility to revert back to the previous version, as the picture quality and the contrast were much better. I don't know any way to natively download the previous version from the iOS app store, so you have to provide me a solution for that please.

I am one of the only 3 people who reviewed the app on the app store with 5 stars. But I am seriously considering to change the review, if this doesn't get fixed very soon, since this is/was a critical tool for me for work.

The only good thing about the update is the new Display selection dropdown menu in the PC app. But it is not worth the other 2 issues mentioned.

Please let me know what your plans are. I hope my feedback is helpful. Let me know if you need further information.

Regards
Daniel

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.


-----

I have to relativize what I wrote in the last email. While the initial smearing which I showed in the example video seems to be fixed, there is a lot of compression artefacts going on when scrolling through text heavy websites for instance.

Why have you changed the was TwomonSE has captured and rendered the image? It was much better than the current version.

Please answer and let me know if you received and aknowledged my feedback.

Regards
Daniel

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

-----


Hello, customer. We are an Easy & Light support team.

We updated it to make it more usable, but an unexpected problem occurred on our side.
Sorry for not checking thoroughly.

PCprogram (EL Display Hub) has been updated.
We have taken measures so that it can be used again with the same performance as the previous version.
Currently the latest version is v4.6.4.0.

We apologize for the inconvenience.
We will do our best to make better products.


Thank you.
Easy & Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Thanks for getting back. But please read my previous emails. I did not complain about the performance on the new version.

Please read what I wrote about the image. It is BRIGHTER than what it should bel I proved it with screenshots. In this state I cannot work with it, as it is not showing the correct brightness value. And now I have no way of reverting back to previous version of the iOS app which is very upsetting.

Please let me know if you read and UNDERSTOOD the problems I described about the IMAGE and the brightness.

Daniel

**Comment by Sienna-lee** [comment]
@Juilliardsong 

해당 사용자가 5일 전 및 하루 전 보내온 메일에 대한 답변을 요청하였습니다.
확인 후 코멘트 부탁드립니다.

**Comment by Juilliardsong** [comment]
사용자 추가 메일
---
Why are you not simply answering? I am a PAYING customer. I PAID for your Twomon SE app, and your recent update made it UNUSABLE for serious work due to the color / brightness difference.

Please answer this simple question:
Have you tested the black level which I pointed out in the previous emails and have you noticed yourself, that the blacks are brighter than they should be. Are you aware of that or not? That is a simple question. If you cannot notice it yourself, just let me know and I can tell you how to test it. But I can say that I tested it on multiple devices. It was definately the update to the new EL PC app which caused this problem.

Just pass that information to your developers and simply let me know if you are aware of that problem or not.

Here I repeat the main problem again:
The color BLACK is NOT TRUE BLACK anymore since your recent updates. I PROVED it with screenshots in my previous emails.

Can you please confirm that you understood what I said here? Or is there a translation issue? I try to write as correct English as I can.

Awaiting an answer.

Regards
Daniel
(a customer who PAID for your products via the iOS app store and is expecting the propper support for that!)
<br>

→ 업데이트 후 밝기 문제가 계속 생긴다는 내용

**Comment by james-kim-Devguru** [comment]
* 수정 이슈 참조 : https://github.com/devguru-co-ltd/EasynLight_Season2/issues/603

**Comment by Juilliardsong** [comment]
아래와 같이 답변함
---
Hello, we are Easy&Light support team.

We are planning to update the mobile app related to screen brightness next week.
I'm sorry for the delay in updating. Please use it after updating.

Thank you.
