### ISSUE TITLE
WIFI 연결 후 끊어짐 반복

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#247]
e-mail:jcnegron@gmail.com<br><br>I need help. The program was working OK. Today the program asked me to update on the PC (windows 10 64 bits) and on my ipad. I had Easy Canvas. After the update, a window keeps appearing in the lower right corner of my desktop pc, alternating intermittently  between &quot;connected to iPad&quot; to disconnected from iPad&quot; and the iPad screen keeps flashing. In the EL Display Hub program , on the other hand, I got the following <br>Error message : Failed to open an encoder codec.<br>Error code : D0020002<br>Could you either point me to how to solve the problem, or tell me how can I go back to the previous working version.<br>Thank you for your prompt response.<br><br>JC Negron<br><br>[EL_Display_825de27e-f163-48fb-a599-4fde10e0020b.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_825de27e-f163-48fb-a599-4fde10e0020b.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 부탁드립니다.
----
한글 원문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

해당 문제를 정확하게 파악하기 위해 태블릿 측 로그가 추가로 필요합니다.

EL Display Hub 문의하기 에서 태블릿 측 로그를 함께 첨부해주시길 바랍니다. 

감사합니다.

Ea​​sy&Light 
```

영문 번역
```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

Additional tablet-side logs are required to accurately identify the problem.

Please attach the tablet log in the EL Display Hub inquiry.

Thank you.

Easy&Light
```

**Comment by AdamPark0030** [comment]
태블릿 앱 로그 요청 메일을 전송했습니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

And where can I find that log?

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
Hello, customer. Easy&Light support team.

We would appreciate it if you could send us your logs by referring to the link below.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy & Light
```

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 로그파일을 첨부하여 회신하였습니다.

----

[Re__[EL_Display_Hub_247]_This_is_the_answer_to_Easy_&_Light's_questions..zip](https://github.com/edh-git/EL_Display_Hub/files/7922221/Re__.EL_Display_Hub_247._This_is_the_answer_to_Easy_._Light.s_questions.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 답변을 회신받지 못했다며 다시 한번 메일을 보내왔습니다.
 

-----

Hello Sirs,

I haven't received any news from you since more than a week ago. I really need  to use my EasyCanvas app, for my distance teaching and for my work. I have already sent to you the files that you asked for. I am attaching them again in case you didn't receive them.
Before the last actualization, the program was working perfectly both on my computer and on my Ipad, and I had the paid app.
I'm not sure if you are still working on a solution. I hope you are on track on why this new version is not working properly on my device, In the meantime,  I would appreciate if you could give me the alternative to return to my previous version, both on my ipad and my windows 10 PC, so I could use the app while you research the reason why the last update is not working.

I appreciate your kind attention.

Yours sincerely,

JC Negron,
EasyCanvas user.

[Re__[EL_Display_Hub_247]_This_is_the_answer_to_Easy_&_Light's_questions. (1).zip](https://github.com/edh-git/EL_Display_Hub/files/7992329/Re__.EL_Display_Hub_247._This_is_the_answer_to_Easy_._Light.s_questions.1.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.
Currently, there are a lot of inquiries about the update, so the response is delayed.

EL Display Hub is an integrated PC program for Twomon SE, Easycanvas Easycanvas Pro.

It seems that the update on the application side does not work properly due to excessive EL Display Hub updates.
After updating the EL Display Hub, visit the App Store or Google Play Store on the tablet side and manually check the application update.

If the tablet does not operate normally even after the application update on the tablet side, the PC program may be damaged during the update process.
After uninstalling the EL Display Hub on the PC side, install a new installer and reinstall it.

[EL Display Hub] installation page: http://www.easynlight.com/en/easycanvas/

If the problem does not improve even after taking the above measures,
Please refer to the log acquisition guide below and ask again with the application log.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

We apologize for the inconvenience.
We will do our best to make better products.

Thank you.

Easy & Light
```
