### ISSUE TITLE
느려짐 현상

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#346]
e-mail:magic4open@qq.com<br><br>the performance is very low in win 11. <br>by the way, the inquiry is not functional in China mainland.<br><br>[EL_Display_d50163fd-c5d0-4186-864b-c3cd87922c5c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d50163fd-c5d0-4186-864b-c3cd87922c5c.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy & Light support team.

We updated it to make it more usable, but an unexpected problem occurred on our side.
Sorry for not checking thoroughly.

PCprogram (EL Display Hub) has been updated.
We have taken measures so that it can be used again with the same performance as the previous version.
Currently the latest version is v4.6.4.0.

We apologize for the inconvenience.
We will do our best to make better products.


Thank you.
Easy & Light
