### ISSUE TITLE
업데이트 후 문제 발생

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#536]
e-mail:nightfairygames@gmail.com<br><br>There seems to be a little issue with the app after the update to El Display Hub that the app just causes display issues on the tablet.<br><br>[EL_Display_6c349276-a074-44bd-b233-89e39f3650ec.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_6c349276-a074-44bd-b233-89e39f3650ec.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

-----



Hello, customer. We are an Easy & Light support team.

We updated it to make it more usable, but an unexpected problem occurred on our side.
Sorry for not checking thoroughly.

PCprogram (EL Display Hub) has been updated.
We have taken measures so that it can be used again with the same performance as the previous version.
Currently the latest version is v4.6.4.0.

We apologize for the inconvenience.
We will do our best to make better products.


Thank you.
Easy & Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Thank you for your response.
