### ISSUE TITLE
세로 모드 사용 불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#548]
e-mail:fady.atallah@outlook.com<br><br>After updating to ELDisplay my setup stopped working. I use a Galaxy Tab S7; and it always worked. The issue is the new app after updating both on Windows and Android it doesn't support Portrait Mode. Please bring back support for Portrait mode... The connection still works for me in Landscape, but not Portrait.<br><br>I hope you can help.<br><br>Thanks and kind regards,<br>Fady Atallah<br><br>[EL_Display_a1a19ad2-c27c-423d-817d-d10776e27125.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a1a19ad2-c27c-423d-817d-d10776e27125.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy & Light support team.

We updated it to make it more usable, but an unexpected problem occurred on our side.
Sorry for not checking thoroughly.

PCprogram (EL Display Hub) has been updated.
We have taken measures so that it can be used again with the same performance as the previous version.
Currently the latest version is v4.6.4.0.

We apologize for the inconvenience.
We will do our best to make better products.


Thank you.
Easy & Light
