### ISSUE TITLE
Manual config without USB

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#718]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:ilya@ilyav.net<br><br>My company does not allow connection of iPad over USB. Is there a way I can configure both server and iPad apps to &quot;find each other&quot; manually somehow, over WiFi?<br><br>[EL_Display_887062d7-18c5-43c2-8d4c-0a605ad82549.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_887062d7-18c5-43c2-8d4c-0a605ad82549.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습닙다.

----


Hello, Customer. We are an Easy & Light support team.
I'm sending this email for your inquiry.


In order to connect wirelessly, it must be connected with a USB cable the first time.
After the first connection, USB connection is not required.
Unfortunately, there is no way to use it without a USB connection.


Sorry for not being able to help.
If you have any additional questions, please feel free to reply.
Thank you.


Easy&Light
