### ISSUE TITLE
Bluetooth keyboard support?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#908]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:as81818@outlook.com<br><br>Hi, I am tryinng to control a windows 10 PC with EasyCanvas on my ipad Pro. I have connected a bluetooth keyboard to the ipad, and the connection is working, but the keyboard input does not get sent to the PC when I'm in the easycanvas app. I need keyboard control in order to do my work. I confirmed the settings allow easycanvas to access bluetooth is enabled. Please help!<br><br>[EL_Display_2297b129-9e7f-4f8f-9c32-0d033f32eb29.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2297b129-9e7f-4f8f-9c32-0d033f32eb29.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.  

If you connect the keyboard to the iPad, you cannot use keystrokes.

Because the keyboard is connected to your iPad, not a PC.

If you want keyboard input, you have to use a bluetooth keyboard or other wire keyboard connecting to a PC separately.


Thanks!


Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 홈페이지를 통해 아래와 같이 동일한 문의를 하였습니다.

----

Title: Bluetooth keyboard support

Questions: Does Easycanvas support bluetooth keyboards connected to the ipad to control a windows PC? I can’t get it to work. Everything else appears to be working perfectly, including the apple pencil. Thank you

**Comment by Sienna-lee** [comment]
아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.  

If you connect the keyboard to the iPad, you cannot use keystrokes.

Because the keyboard is connected to your iPad, not a PC.

If you want keyboard input, you have to use a bluetooth keyboard or other wire keyboard connecting to a PC separately.


Thank you.


Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Thank you for the response. This is unfortunate. It isn’t very useful to have wifi control of the PC if I still have to stay within range of the computer to use a keyboard. I hope you will consider adding this important feature. I will have to find another app to use for my purposes until then.

Thank you

Adam
